// src/app/api/messages/create/route.ts
import { NextRequest, NextResponse } from 'next/server';
import type { SupabaseClient } from '@supabase/supabase-js';
import { Message, MessageStatus, MessageType } from '@/types/messaging';
import {
  IMessageRepository,
  IConversationRepository,
  IMessageAttachmentUploadRepository,
  AttachmentLinkError,
} from '@/repositories/interfaces';
import {
  SupabaseMessageRepository,
  SupabaseConversationRepository,
  SupabaseMessageAttachmentUploadRepository,
} from '@/repositories/implementations/supabase';
import { isAuthzFailure, jsonError, requireConversationParticipant } from '@/lib/auth/authorize';
import { enforceRateLimit } from '@/lib/auth/rate-limit';
import { MAX_ATTACHMENTS_PER_MESSAGE, attachmentMessageType } from '@/lib/messaging/attachment-policy';
import { validateUploadsForLink } from '@/lib/messaging/attachment-uploads';

// Audit S-04: cap message payload size server-side.
const MAX_CONTENT_LENGTH = 8192;

const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

type MessageCreateData = Omit<Message, 'id' | 'timestamp' | 'reactions' | 'attachments' | 'isEdited'>;

/**
 * Phase 4 FR-024: optional composition key generated by the drawer composer
 * and resent on every retry of the same composition. Absent (the published
 * app) → legacy create; present → at most one message per key, sender, and
 * conversation.
 */
function parseClientMessageId(value: unknown): { ok: true; value: string | undefined } | { ok: false } {
  if (value === undefined || value === null) {
    return { ok: true, value: undefined };
  }
  if (typeof value !== 'string' || !UUID_PATTERN.test(value)) {
    return { ok: false };
  }
  return { ok: true, value: value.toLowerCase() };
}

const TOO_MANY_ATTACHMENTS_MESSAGE = `A message can carry at most ${MAX_ATTACHMENTS_PER_MESSAGE} attachments`;

/**
 * Phase 4 T12 (FR-008): optional ids of the caller's pending uploads
 * (POST /api/messages/upload) to attach. Absent or empty → no attachments.
 */
function parseAttachmentIds(
  value: unknown
): { ok: true; value: string[] | undefined } | { ok: false; code: string; message: string } {
  if (value === undefined || value === null) {
    return { ok: true, value: undefined };
  }
  if (!Array.isArray(value) || value.some((id) => typeof id !== 'string' || !UUID_PATTERN.test(id))) {
    return { ok: false, code: 'INVALID_ATTACHMENT_ID', message: 'attachmentIds must be an array of upload ids' };
  }
  const ids = (value as string[]).map((id) => id.toLowerCase());
  if (ids.length === 0) {
    return { ok: true, value: undefined };
  }
  if (ids.length > MAX_ATTACHMENTS_PER_MESSAGE) {
    return { ok: false, code: 'TOO_MANY_ATTACHMENTS', message: TOO_MANY_ATTACHMENTS_MESSAGE };
  }
  if (new Set(ids).size !== ids.length) {
    return { ok: false, code: 'DUPLICATE_ATTACHMENT', message: 'attachmentIds must not repeat an upload' };
  }
  return { ok: true, value: ids };
}

/**
 * A replayed key must carry the same composition: content, reply target, the
 * same attachment set (attachment id = upload id), and — for messages without
 * attachments — the same type (attachment messages derive their type from
 * their attachments).
 */
function isSameComposition(
  stored: Message,
  storedAttachmentIdList: readonly string[],
  expected: { content: string; type?: MessageType; replyToId?: string; attachmentIds: readonly string[] }
): boolean {
  const storedAttachmentIds = [...storedAttachmentIdList].sort();
  const expectedAttachmentIds = [...expected.attachmentIds].sort();
  return (
    stored.content === expected.content &&
    (expected.type === undefined || stored.type === expected.type) &&
    (stored.replyToId ?? null) === (expected.replyToId ?? null) &&
    storedAttachmentIds.length === expectedAttachmentIds.length &&
    storedAttachmentIds.every((id, index) => id === expectedAttachmentIds[index])
  );
}

// Responses carry the message, its attachments and reactions — not other
// users' pins or stars, which findById (service client) also loads.
function asResponseMessage(message: Message): Message {
  return { ...message, pins: undefined, stars: undefined };
}

function clientKeyReused() {
  return jsonError(409, 'CLIENT_MESSAGE_ID_REUSED', 'clientMessageId was already used for a different message');
}

function attachmentNotFound() {
  return jsonError(400, 'ATTACHMENT_NOT_FOUND', 'An attachment was not found; upload it again');
}

function attachmentLinkFailure(error: AttachmentLinkError) {
  switch (error.code) {
    case 'NOT_PARTICIPANT':
      return jsonError(403, 'NOT_PARTICIPANT', 'You are not a participant of this conversation');
    case 'ATTACHMENT_COUNT_INVALID':
      return jsonError(400, 'TOO_MANY_ATTACHMENTS', TOO_MANY_ATTACHMENTS_MESSAGE);
    case 'ATTACHMENT_DUPLICATE':
      return jsonError(400, 'DUPLICATE_ATTACHMENT', 'attachmentIds must not repeat an upload');
    case 'ATTACHMENT_UPLOAD_NOT_FOUND':
      return attachmentNotFound();
    case 'INVALID_REPLY_TARGET':
      return jsonError(400, 'INVALID_REPLY_TARGET', 'replyToId must reference a message in the same conversation');
    case 'VOICE_NOTE_NOT_ALONE':
      return voiceNoteNotAlone();
  }
}

function voiceNoteNotAlone() {
  return jsonError(400, 'VOICE_NOTE_NOT_ALONE', 'A voice note must be the only attachment of its message');
}

/**
 * Creates the message and links its pending uploads in one transaction
 * (BR-007: never visible partially attached). The uploads must belong to the
 * caller for this conversation and pass the attachment policy on their STORED
 * objects.
 */
async function createWithAttachments(
  serviceClient: SupabaseClient,
  messageRepository: IMessageRepository,
  conversationRepository: IConversationRepository,
  uploads: IMessageAttachmentUploadRepository,
  messageData: Omit<MessageCreateData, 'type'>,
  attachmentIds: string[],
  clientMessageId: string | undefined
): Promise<{ response: NextResponse; created: boolean }> {
  const owned = await uploads.findOwned(attachmentIds, messageData.senderId, messageData.conversationId);

  let type = MessageType.FILE;
  const allUploadsPending = owned.length === attachmentIds.length;
  if (allUploadsPending) {
    // Phase 4 T15: a voice note travels alone (the database enforces it too).
    if (owned.length > 1 && owned.some((upload) => upload.duration !== undefined)) {
      return { response: voiceNoteNotAlone(), created: false };
    }
    const violation = await validateUploadsForLink(serviceClient, owned);
    if (violation) {
      return { response: jsonError(violation.status, violation.code, violation.message), created: false };
    }
    type = attachmentMessageType(owned.map((upload) => upload.type));
  } else if (!clientMessageId) {
    // Unknown, another user's, another conversation's, cancelled, or sent.
    return { response: attachmentNotFound(), created: false };
  }
  // With a key and missing uploads the database decides: a replay of a
  // committed create (its uploads were consumed) or ATTACHMENT_NOT_FOUND.

  let outcome: { messageId: string; created: boolean };
  try {
    outcome = await uploads.createMessageWithAttachments({ ...messageData, type }, attachmentIds, clientMessageId);
  } catch (error) {
    if (error instanceof AttachmentLinkError) {
      return { response: attachmentLinkFailure(error), created: false };
    }
    throw error;
  }

  if (outcome.created && !allUploadsPending) {
    // The database can only replay or refuse when uploads were missing here.
    throw new Error('create_message_with_attachments linked uploads that failed the policy pre-check');
  }
  if (outcome.created) {
    // Committed: bump activity now so a failed read-back below (500, then a
    // 200 replay on retry) never skips the recipients' badge refresh.
    await touchConversation(conversationRepository, messageData.conversationId);
  }

  const stored = await messageRepository.findById(outcome.messageId);
  if (!stored) {
    throw new Error(`Message ${outcome.messageId} not found after create`);
  }
  // Read strictly: findById degrades attachment read errors to [] (which would
  // turn a genuine replay into a false 409 or answer 201 without files).
  const linkedIds = await uploads.listLinkedAttachmentIds(outcome.messageId);
  if (!outcome.created) {
    if (!isSameComposition(stored, linkedIds, { ...messageData, attachmentIds })) {
      return { response: clientKeyReused(), created: false };
    }
    return { response: NextResponse.json({ message: asResponseMessage(stored) }, { status: 200 }), created: false };
  }
  if ((stored.attachments ?? []).length !== linkedIds.length) {
    // The message and its files are committed; a retry with the same key
    // replays it (200) once the read succeeds.
    throw new Error(`Attachments of message ${outcome.messageId} could not be read after create`);
  }
  return { response: NextResponse.json({ message: asResponseMessage(stored) }, { status: 201 }), created: true };
}

// Update conversation last activity. Besides ordering the list, this UPDATE on
// conversations is what fires useConversationRealtime's cache invalidation so
// recipients' unread badges refresh. Unread counts are derived from
// conversation_members.last_read_at (Phase 2.2) — nothing to increment here.
async function touchConversation(conversationRepository: IConversationRepository, conversationId: string) {
  try {
    await conversationRepository.updateLastActivityTimestamp(conversationId);
  } catch (updateError) {
    console.warn('Failed to update conversation activity:', updateError);
    // Don't fail the request if conversation update fails
  }
}

/**
 * POST /api/messages/create
 * Body: { conversationId, content, type?, replyToId?, clientMessageId?, attachmentIds? }
 * `content` may be empty (or omitted) only when `attachmentIds` lists 1–5 of
 * the caller's pending uploads for this conversation (Phase 4 T12); the type
 * of such a message is derived from its attachments (image or file; a voice
 * note — Phase 4 T15 — is the only attachment of a file message).
 * 201 created; 200 replay of `clientMessageId` (nothing inserted or linked);
 * 409 CLIENT_MESSAGE_ID_REUSED when the replay's composition differs.
 */
export async function POST(request: NextRequest) {
  try {
    let body: Record<string, unknown>;
    try {
      body = await request.json();
    } catch {
      return jsonError(400, 'BAD_REQUEST', 'Invalid JSON payload');
    }
    if (typeof body !== 'object' || body === null || Array.isArray(body)) {
      return jsonError(400, 'BAD_REQUEST', 'Invalid JSON payload');
    }

    const attachmentIds = parseAttachmentIds(body.attachmentIds);
    if (!attachmentIds.ok) {
      return jsonError(400, attachmentIds.code, attachmentIds.message);
    }
    const hasAttachments = attachmentIds.value !== undefined;

    const conversationId = typeof body.conversationId === 'string' ? body.conversationId : null;
    const rawContent = body.content === undefined && hasAttachments ? '' : body.content;
    if (!conversationId || typeof rawContent !== 'string') {
      return jsonError(400, 'BAD_REQUEST', 'Missing required fields: conversationId, content');
    }

    const trimmedContent = rawContent.trim();
    if (trimmedContent.length === 0 && !hasAttachments) {
      return jsonError(400, 'BAD_REQUEST', 'Content must not be empty');
    }
    if (trimmedContent.length > MAX_CONTENT_LENGTH) {
      return jsonError(413, 'CONTENT_TOO_LARGE', `Content exceeds the ${MAX_CONTENT_LENGTH} character limit`);
    }

    const clientMessageId = parseClientMessageId(body.clientMessageId);
    if (!clientMessageId.ok) {
      return jsonError(400, 'INVALID_CLIENT_MESSAGE_ID', 'clientMessageId must be a UUID');
    }

    const ctx = await requireConversationParticipant(conversationId);
    if (isAuthzFailure(ctx)) {
      return ctx.errorResponse;
    }
    const { serviceClient, dbUser, conversation } = ctx;

    const rateLimited = await enforceRateLimit(serviceClient, dbUser.id, 'message:create');
    if (rateLimited) {
      return rateLimited;
    }

    const messageRepository: IMessageRepository = new SupabaseMessageRepository(serviceClient);
    const conversationRepository: IConversationRepository = new SupabaseConversationRepository(serviceClient);

    // Audit S-04: replyToId must reference a message in the SAME conversation.
    let replyToId: string | undefined;
    if (body.replyToId !== undefined && body.replyToId !== null) {
      if (typeof body.replyToId !== 'string') {
        return jsonError(400, 'BAD_REQUEST', 'replyToId must be a string');
      }
      const { data: replyTarget, error: replyError } = await serviceClient
        .from('messages')
        .select('id, conversation_id')
        .eq('id', body.replyToId)
        .maybeSingle();
      if (replyError) {
        console.error('Failed to validate replyToId:', replyError.message);
        return jsonError(500, 'INTERNAL_ERROR', 'Failed to create message');
      }
      if (!replyTarget || replyTarget.conversation_id !== conversation.id) {
        return jsonError(400, 'INVALID_REPLY_TARGET', 'replyToId must reference a message in the same conversation');
      }
      replyToId = replyTarget.id;
    }

    const baseMessageData: Omit<MessageCreateData, 'type'> = {
      conversationId: conversation.id,
      senderId: dbUser.id,
      content: trimmedContent,
      // Audit S-04: never trust client-supplied status (pre-marked read/delivered).
      status: MessageStatus.SENT,
      replyToId,
    };

    if (attachmentIds.value) {
      const result = await createWithAttachments(
        serviceClient,
        messageRepository,
        conversationRepository,
        new SupabaseMessageAttachmentUploadRepository(serviceClient),
        baseMessageData,
        attachmentIds.value,
        clientMessageId.value
      );
      return result.response;
    }

    const safeType: MessageType = Object.values(MessageType).includes(body.type as MessageType)
      ? (body.type as MessageType)
      : MessageType.TEXT;
    const messageData: MessageCreateData = { ...baseMessageData, type: safeType };

    let createdMessage: Message;
    if (clientMessageId.value) {
      const outcome = await messageRepository.createWithClientKey(messageData, clientMessageId.value);
      if (!outcome.created) {
        // A retry of a composition whose create already committed (e.g. its
        // response was lost): answer with the stored message, insert nothing.
        // The key is per composition, so a different payload — including a
        // stored message that carries attachments — is a client bug.
        const stored = (await messageRepository.findById(outcome.message.id)) ?? outcome.message;
        const linkedIds = await new SupabaseMessageAttachmentUploadRepository(serviceClient).listLinkedAttachmentIds(stored.id);
        if (!isSameComposition(stored, linkedIds, { ...messageData, attachmentIds: [] })) {
          return clientKeyReused();
        }
        return NextResponse.json({ message: asResponseMessage(stored) }, { status: 200 });
      }
      createdMessage = outcome.message;
    } else {
      createdMessage = await messageRepository.create(messageData);
    }

    await touchConversation(conversationRepository, conversation.id);

    return NextResponse.json({ message: createdMessage }, { status: 201 });
  } catch (error) {
    console.error('Error creating message:', error);
    return jsonError(500, 'INTERNAL_ERROR', 'Failed to create message');
  }
}
